name: Bug Report 🐛🔧
description: Report an issue or bug in the project.
title: "[BUG] : "

body:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description 🐛
      description: Provide a detailed description of the issue or bug you encountered.
      placeholder: Describe the problem, its impact, and any relevant details (e.g., error messages, affected components, etc.).
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce 🔍
      description: Provide clear steps to reproduce the bug.
      placeholder: List the steps here, e.g., 1. Go to..., 2. Click on..., 3. See error.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior ✅
      description: Describe what you expected to happen instead of the observed behavior.
      placeholder: Clearly state the correct or expected outcome.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior ❌
      description: Describe what actually happened, including any error messages or anomalies.
      placeholder: Clearly state what occurred instead of the expected outcome.
    validations:
      required: true

  - type: dropdown
    id: contribution_program
    attributes:
      label: Select the open-source program you're contributing to 
      multiple: true
      options:
        - cwoc24-25
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution_guidelines
    attributes:
      label: Adherence to Contribution Guidelines
      description: By submitting this issue, you agree to abide by our [CONTRIBUTING GUIDELINES].
      options:
        - label: I adhere to the [CONTRIBUTING GUIDELINES] of this project.
          required: true
