name: Enhancement Proposal 💡🛠️
description: Suggest improvements to existing features or UI.
title: "[ENHANCEMENT] : "

body:
  - type: textarea
    id: enhancement_description
    attributes:
      label: Enhancement Description 🛠️
      description: Provide details about the improvement you'd like to propose.
      placeholder: Describe what you want to improve, why it's necessary, and how it will enhance the project.
    validations:
      required: true

  - type: dropdown
    id: contribution_program
    attributes:
      label: Select the open-source program you're contributing to 
      multiple: true
      options:
        - cwoc24-25
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution_guidelines
    attributes:
      label: Adherence to Contribution Guidelines
      description: By submitting this issue, you agree to abide by our [CONTRIBUTING GUIDELINES].
      options:
        - label: I adhere to the [CONTRIBUTING GUIDELINES] of this project.
          required: true
