name: Changes in Frontend 🖌️✨
description: Enhance and add new functionalities to the existing frontend of the website.
title: "[FRONTEND Enhancement] : "

body:
  - type: textarea
    id: frontend_changes_description
    attributes:
      label: Quick Description ✨
      description: Provide a brief description of the improvements or new features you plan to implement in the frontend.
      placeholder: Please provide a short summary of the changes or features you intend to add! Ensure to list at least 2 enhancements for your PR to be reviewed and merged.
    validations:
      required: true

  - type: dropdown
    id: contribution_program
    attributes:
      label: Select the open-source program you're contributing to 
      multiple: true
      options:
        - cwoc24-25
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution_guidelines
    attributes:
      label: Adherence to Contribution Guidelines
      description: By submitting this issue, you agree to abide by our [CONTRIBUTING GUIDELINES].
      options:
        - label: I adhere to the [CONTRIBUTING GUIDELINES] of this project.
          required: true
