name: New Feature Request 🚀✨
description: Propose a new feature to enhance the website.
title: "[FEATURE] : "

body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description ✨
      description: Provide a detailed description of the new feature you'd like to add to the project.
      placeholder: Describe the functionality, purpose, and how it will benefit the project. Include any technical details, if possible.
    validations:
      required: true

  - type: dropdown
    id: contribution_program
    attributes:
      label: Select the open-source program you're contributing to 
      multiple: true
      options:
        - cwoc24-25
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution_guidelines
    attributes:
      label: Adherence to Contribution Guidelines
      description: By submitting this issue, you agree to abide by our [CONTRIBUTING GUIDELINES].
      options:
        - label: I adhere to the [CONTRIBUTING GUIDELINES] of this project.
          required: true
